en:
  closure_tree:
    loop_error: 'can not refer to himself'
